Struggling with BASH 4.0 and below

diff --git a/check b/check
--- a/check
+++ b/check
@@ -1,6 +1,71 @@
 #! /usr/bin/env bash
 
+log() {
+  echo "$@" >> log.log
+  return 0
+}
+
+logf() {
+  printf "$@" >> log.log
+  return 0
+}
+
+__debugTrap() {
+  [[ "$2" = "log "* ]] && return 0
+  [[ "$2" = "__errOrExitTrap"* ]] && return 0
+  [ "$5" = "__errOrExitTrap" ] && return 0
+  [ "$5" = "log" ] && return 0
+  log "(new) DEBUG [$1] [$2] [$3] [$4] [$5]"
+  if (( $1 == 0 )); then
+    shift
+    __check__debugTrap_previousInfo=("$@")
+  fi
+  return 0
+}
+
+__errOrExitTrap() {
+  log "---> ERR/EXIT TRAP [$1] $*"
+  local __check__newline=$'\n'
+  CHECK_FAILED_STACKTRACE=
+  if (( $# > 0 )); then
+    CHECK_FAILED_STACKTRACE+="  \e[${CHECK_COLOR_NEUTRAL:-34}m$2\e[0m:\e[${CHECK_COLOR_NEUTRAL:-34}m$3 $4${__check__newline}\e[0m"
+    CHECK_FAILED_STACKTRACE+="  \e[${CHECK_COLOR_STACKTRACE:-33}m$( sed "${3}q;d" "$2" | sed "s/^ *//g" | sed "s/^/  /" )\e[0m${__check__newline}"
+  else
+    for (( i = 0 ; i < ${#BASH_LINENO[0]} ; i++ )); do
+      CHECK_FAILED_STACKTRACE+="  \e[${CHECK_COLOR_NEUTRAL:-34}m${BASH_SOURCE[i+1]}\e[0m:\e[${CHECK_COLOR_NEUTRAL:-34}m${BASH_LINENO[i]} ${FUNCNAME[i+1]}${__check__newline}\e[0m"
+      CHECK_FAILED_STACKTRACE+="  \e[${CHECK_COLOR_STACKTRACE:-33}m$( sed "${BASH_LINENO[i]}q;d" "${BASH_SOURCE[i+1]}" | sed "s/^ *//g" | sed "s/^/  /" )\e[0m${__check__newline}"
+    done
+  fi
+  [ "${CHECK_STACKTRACE:-true}" = true ] && declare -p CHECK_FAILED_STACKTRACE
+  return 1
+}
+
+# __errTrap() {
+#   local retCode=$?
+#   log "**** ERROR TRAP ($retCode) [$1] $*"
+#   __exitTrap "$@"
+# }
+
+# __errTrap() {
+#   log "(new) ERROR TRAP $*"
+#   local __check__newline=$'\n'
+#   CHECK_FAILED_STACKTRACE=
+#   if (( $# > 0 )); then
+#     CHECK_FAILED_STACKTRACE+="  \e[${CHECK_COLOR_NEUTRAL:-34}m$2\e[0m:\e[${CHECK_COLOR_NEUTRAL:-34}m$3 $4${__check__newline}\e[0m"
+#     CHECK_FAILED_STACKTRACE+="  \e[${CHECK_COLOR_STACKTRACE:-33}m$( sed "${3}q;d" "$2" | sed "s/^ *//g" | sed "s/^/  /" )\e[0m${__check__newline}"
+#   else
+#     for (( i = 0 ; i < ${#BASH_LINENO[0]} ; i++ )); do
+#       CHECK_FAILED_STACKTRACE+="  \e[${CHECK_COLOR_NEUTRAL:-34}m${BASH_SOURCE[i+1]}\e[0m:\e[${CHECK_COLOR_NEUTRAL:-34}m${BASH_LINENO[i]} ${FUNCNAME[i+1]}${__check__newline}\e[0m"
+#       CHECK_FAILED_STACKTRACE+="  \e[${CHECK_COLOR_STACKTRACE:-33}m$( sed "${BASH_LINENO[i]}q;d" "${BASH_SOURCE[i+1]}" | sed "s/^ *//g" | sed "s/^/  /" )\e[0m${__check__newline}"
+#     done
+#   fi
+#   [ "${CHECK_STACKTRACE:-true}" = true ] && declare -p CHECK_FAILED_STACKTRACE
+#   return 1
+# }
+
 check() {
+  log "==========================================================================="
+  log "CHECK() $*"
   local -r CHECK_VERSION="1.0.0"; local CHECK_FILE="${CHECK_FILE}" CHECK_TEST="${CHECK_TEST}"
   if [ "$1" = -- ]; then
     shift
@@ -23,6 +88,7 @@ check() {
             eval "$( eval printf '%s\\n' "$__check__line" )"
           fi
         done <<< "$1"
+        log "$1"
         case "$CHECK_EXITCODE" in
           0) echo -e "[\e[${CHECK_COLOR_PASS:-32}mPASS\e[0m] $CHECK_TEST"; (( CHECK_PASSED = CHECK_PASSED + 1 )) ;;
           *) echo -e "[\e[${CHECK_COLOR_FAIL:-31}mFAIL\e[0m] $CHECK_TEST"; (( CHECK_FAILED = CHECK_FAILED + 1 )) ;;
@@ -63,45 +129,54 @@ check() {
         } 2>&1 )"
         return 0
         ;;
+      
       runTestFunction)
         shift; CHECK_FILE="$1"; shift; CHECK_TEST="$1"; shift; source "$CHECK_FILE" || return $?;
-        [ "${CHECK_SET_E:-true}" = true ] && set -eE
+        # [ "${CHECK_SET_E:-true}" = true ] && set -eE
         # if (( ${BASH_VERSINFO[0]} < 5 )); then
           local -a __check__debugTrap_previousInfo=()
-          trap 'check -- debugTrap $? "$BASH_COMMAND" "${BASH_SOURCE[0]}" "$LINENO" "${FUNCNAME[0]}"' DEBUG
-          set -o functrace
-          trap 'check -- errTrap "${__check__debugTrap_previousInfo[@]}"' ERR
         # else
         #   trap 'check -- errTrap' ERR
         # fi
-        "$CHECK_TEST"; return $? ;;
-      debugTrap)
-        shift
-        if (( $1 == 0 )); then
-          shift
-          __check__debugTrap_previousInfo=("$@")
-        else
-          local __check__newline=$'\n'
-          CHECK_FAILED_STACKTRACE="  \e[${CHECK_COLOR_NEUTRAL:-34}m${__check__debugTrap_previousInfo[1]}\e[0m:\e[${CHECK_COLOR_NEUTRAL:-34}m${__check__debugTrap_previousInfo[2]} ${__check__debugTrap_previousInfo[3]}${__check__newline}\e[0m"
-          CHECK_FAILED_STACKTRACE+="  \e[${CHECK_COLOR_STACKTRACE:-33}m$( sed "${__check__debugTrap_previousInfo[2]}q;d" "${__check__debugTrap_previousInfo[1]}" | sed "s/^ *//g" | sed "s/^/  /" )\e[0m${__check__newline}"
-        fi
-        return 0
+
+        trap '__debugTrap $? "$BASH_COMMAND" "${BASH_SOURCE[0]}" "$LINENO" "${FUNCNAME[0]}"' DEBUG
+        trap '__errOrExitTrap "${__check__debugTrap_previousInfo[@]}"' ERR EXIT
+
+        # set -eE
+        set -o pipefail
+        set -o functrace
+        "$CHECK_TEST"
+        trap - DEBUG ERR EXIT
+        return $?
         ;;
-      errTrap)
-        local __check__newline=$'\n'
-        CHECK_FAILED_STACKTRACE=
-        if (( $# > 1 )); then
-          CHECK_FAILED_STACKTRACE+="  \e[${CHECK_COLOR_NEUTRAL:-34}m$3\e[0m:\e[${CHECK_COLOR_NEUTRAL:-34}m$4 $5${__check__newline}\e[0m"
-          CHECK_FAILED_STACKTRACE+="  \e[${CHECK_COLOR_STACKTRACE:-33}m$( sed "${4}q;d" "$3" | sed "s/^ *//g" | sed "s/^/  /" )\e[0m${__check__newline}"
-        else
-          for (( i = 0 ; i < ${#BASH_LINENO[0]} ; i++ )); do
-            CHECK_FAILED_STACKTRACE+="  \e[${CHECK_COLOR_NEUTRAL:-34}m${BASH_SOURCE[i+1]}\e[0m:\e[${CHECK_COLOR_NEUTRAL:-34}m${BASH_LINENO[i]} ${FUNCNAME[i+1]}${__check__newline}\e[0m"
-            CHECK_FAILED_STACKTRACE+="  \e[${CHECK_COLOR_STACKTRACE:-33}m$( sed "${BASH_LINENO[i]}q;d" "${BASH_SOURCE[i+1]}" | sed "s/^ *//g" | sed "s/^/  /" )\e[0m${__check__newline}"
-          done
-        fi
-        [ "${CHECK_STACKTRACE:-true}" = true ] && declare -p CHECK_FAILED_STACKTRACE
-        return 1
-        ;;
+
+      # debugTrap)
+      #   log "DEBUG $*"
+      #   shift
+      #   if (( $1 == 0 )); then
+      #     shift
+      #     __check__debugTrap_previousInfo=("$@")
+      #   # else
+      #   #   (( ${BASH_VERSINFO[0]} < 4 )) || { (( ${BASH_VERSINFO[0]} == 4)) && (( ${BASH_VERSINFO[1]} < 1 )); } && return 1
+      #   fi
+      #   return 0
+      #   ;;
+      # errTrap)
+      #   log "ERROR TRAP $*"
+      #   local __check__newline=$'\n'
+      #   CHECK_FAILED_STACKTRACE=
+      #   if (( $# > 1 )); then
+      #     CHECK_FAILED_STACKTRACE+="  \e[${CHECK_COLOR_NEUTRAL:-34}m$3\e[0m:\e[${CHECK_COLOR_NEUTRAL:-34}m$4 $5${__check__newline}\e[0m"
+      #     CHECK_FAILED_STACKTRACE+="  \e[${CHECK_COLOR_STACKTRACE:-33}m$( sed "${4}q;d" "$3" | sed "s/^ *//g" | sed "s/^/  /" )\e[0m${__check__newline}"
+      #   else
+      #     for (( i = 0 ; i < ${#BASH_LINENO[0]} ; i++ )); do
+      #       CHECK_FAILED_STACKTRACE+="  \e[${CHECK_COLOR_NEUTRAL:-34}m${BASH_SOURCE[i+1]}\e[0m:\e[${CHECK_COLOR_NEUTRAL:-34}m${BASH_LINENO[i]} ${FUNCNAME[i+1]}${__check__newline}\e[0m"
+      #       CHECK_FAILED_STACKTRACE+="  \e[${CHECK_COLOR_STACKTRACE:-33}m$( sed "${BASH_LINENO[i]}q;d" "${BASH_SOURCE[i+1]}" | sed "s/^ *//g" | sed "s/^/  /" )\e[0m${__check__newline}"
+      #     done
+      #   fi
+      #   [ "${CHECK_STACKTRACE:-true}" = true ] && declare -p CHECK_FAILED_STACKTRACE
+      #   return 1
+      #   ;;
       *) echo "check: unknown private command '$*'" >&2; return 1 ;;
     esac
     return 0
