TAP Specification (microtap v1.3.0)

diff --git a/microtap b/microtap
--- a/microtap
+++ b/microtap
@@ -1,5 +1,5 @@
 #! /usr/bin/env bash
-MICROTAP_VERSION=1.2.0; [ "$1" = --version ] && { echo "microtap version $MICROTAP_VERSION"; exit 0; }
+MICROTAP_VERSION=1.3.0; [ "$1" = --version ] && { echo "microtap version $MICROTAP_VERSION"; exit 0; }
 [ "$1" = --list ] && [ -f "$2" ] && { source "$2"; if declare -pF | awk '{print $3}' | grep -i '^test\|^spec' 2>/dev/null; then exit 0; else exit $?; fi; }
 runAll() { if [ -z "${1:-}" ]; then return 0; fi; if __spec__functions="$( declare -pF | awk '{print $3}' | grep -i "$1" 2>/dev/null )"; then for __spec__fn in $__spec__functions; do $__spec__fn; done; fi; }
 recordCmd() { spec_return=$?; if (( $1 == 0 )) && [ "$2" != "$0" ]; then if [ -z "$__spec__testDone" ]; then CMD_INFO=("${@:1}"); fi; fi; return $spec_return; }
@@ -9,14 +9,14 @@ recordCmd() { spec_return=$?; if (( $1 == 0 )) && [ "$2" != "$0" ]; then if [ -z
   runAll "^setup\|^before"; "$3"; exit $?; }
 declare -i TEST_COUNT=0; for SPEC_FILE; do __spec__testCount="$("$0" --list "$SPEC_FILE" 2>/dev/null | wc -l)"; (( TEST_COUNT += __spec__testCount )); done
 (( TEST_COUNT > 0 )) && echo "1..$TEST_COUNT" || exit 0
-for SPEC_FILE; do declare -i PASSED=0; declare -i FAILED=0; 
+for SPEC_FILE; do declare -i PASSED=0; declare -i FAILED=0; declare -i TEST_NUMBER=0
   if [ -f "$SPEC_FILE" ]; then
-    for SPEC_TEST in $("$0" --list "$SPEC_FILE" 2>/dev/null); do
+    for SPEC_TEST in $("$0" --list "$SPEC_FILE" 2>/dev/null); do (( TEST_NUMBER++ ))
       SPEC_TEST_OUTPUT="$({ STDERR="$({ STDOUT="$( "$0" --run "$SPEC_FILE" "$SPEC_TEST" )"; } 2>&1; declare -i EXITCODE=$?; declare -p STDOUT >&2; declare -p EXITCODE >&2; exit $EXITCODE;)"; declare -p STDERR; exit 0; } 2>&1 )"
       eval "$SPEC_TEST_OUTPUT";
       [[ "$STDOUT" =~ .*(declare[[:space:]]-a[[:space:]]CMD_INFO=[\']?\(.*)$ ]] && __spec_lastCmdText__="${BASH_REMATCH[1]}"
       [ -n "$__spec_lastCmdText__" ] && { eval "$__spec_lastCmdText__"; STDOUT="${STDOUT%"$__spec_lastCmdText__"}"; STDOUT="${STDOUT%$'\n'}"; }
-      (( EXITCODE == 0 )) && { (( PASSED++ )); echo -e "ok - $SPEC_TEST"; } || { (( FAILED++ )); echo -e "not ok - $SPEC_TEST"; }
+      (( EXITCODE == 0 )) && { (( PASSED++ )); echo -e "ok $TEST_NUMBER - $SPEC_TEST"; } || { (( FAILED++ )); echo -e "not ok $TEST_NUMBER - $SPEC_TEST"; }
       (( EXITCODE != 0 )) || [ "$VERBOSE" = true ] && {
         [ -n "$STDOUT" ] && { echo -e "# Standard Output:"; echo -e "$( echo -e "$STDOUT" | sed 's/^/#  /' )"; }
         [ -n "$STDERR" ] && { echo -e "# Standard Error:"; echo -e "$( echo -e "$STDERR" | sed 's/^/#  /' )"; }
