Support dynamic in-memory spec functions (v1.9.0)

diff --git a/microtap b/microtap
--- a/microtap
+++ b/microtap
@@ -1,6 +1,6 @@
 #! /usr/bin/env bash
 # Copyright (c) 2021 Rebecca Taylor - MIT License
-MICROTAP_VERSION=1.8.1; [ "$1" = --version ] && { echo "microtap version $MICROTAP_VERSION"; exit 0; }
+MICROTAP_VERSION=1.9.0; [ "$1" = --version ] && { echo "microtap version $MICROTAP_VERSION"; exit 0; }
 [ "$1" = --list ] && [ -f "$2" ] && { source "$2"; if declare -pF | awk '{print $3}' | grep -i '^test\|^spec' 2>/dev/null; then exit 0; else exit $?; fi; }
 runAll() { if [ -z "${1:-}" ]; then return 0; fi; if __spec__functions="$( declare -pF | awk '{print $3}' | grep -i "$1" 2>/dev/null )"; then for __spec__fn in $__spec__functions; do $__spec__fn; done; fi; }
 recordCmd() { spec_return=$?; if (( $1 == 0 )) && [ "$2" != "$0" ] && { [ -z "${__spec__sourcedOk:-}" ] || [ "$4" = "$SPEC_TEST" ]; } && [ -z "${__spec__testDone:-}" ]; then CMD_INFO=("${@:1}"); fi; if [ "$4" = "${CMD_INFO[3]:-}" ]; then return $spec_return; else return 0; fi; }
@@ -18,15 +18,14 @@ for SPEC_FILE in "${SPEC_FILES[@]}"; do
       eval "$SPEC_TEST_OUTPUT";
       [[ "$STDOUT" =~ .*(declare[[:space:]]-a[[:space:]]CMD_INFO=[\']?\(.*)$ ]] && __spec_lastCmdText__="${BASH_REMATCH[1]}"
       [ -n "$__spec_lastCmdText__" ] && { eval "$__spec_lastCmdText__"; STDOUT="${STDOUT%"$__spec_lastCmdText__"}"; STDOUT="${STDOUT%$'\n'}"; }
-      (( EXITCODE == 0 )) && { (( PASSED++ )); echo -e "ok $TEST_NUMBER - $SPEC_TEST"; } || { (( FAILED++ )); echo -e "not ok $TEST_NUMBER - $SPEC_TEST"; }
+      (( EXITCODE == 0 )) && { (( PASSED++ )); echo "ok $TEST_NUMBER - $SPEC_TEST"; } || { (( FAILED++ )); echo "not ok $TEST_NUMBER - $SPEC_TEST"; }
       (( EXITCODE != 0 )) || [ "${VERBOSE:-}" = true ] && {
-        [ -n "$STDOUT" ] && { echo -e "# Standard Output:"; echo -e "$( echo -e "$STDOUT" | sed 's/^/#  /' )"; }
-        [ -n "$STDERR" ] && { echo -e "# Standard Error:"; echo -e "$( echo -e "$STDERR" | sed 's/^/#  /' )"; }
+        [ -n "$STDOUT" ] && { echo "# Standard Output:"; echo "$( echo "$STDOUT" | sed 's/^/#  /' )"; }
+        [ -n "$STDERR" ] && { echo "# Standard Error:"; echo "$( echo "$STDERR" | sed 's/^/#  /' )"; }
         (( ${#CMD_INFO[@]} > 2 )) && { (( EXITCODE != 0 )) || [ "$STACKTRACE" = true ]; } && {
-          echo -e "# Stacktrace:"; echo -e "#   ${CMD_INFO[1]}:${CMD_INFO[2]} ${CMD_INFO[3]}";
-          [ -f "${CMD_INFO[1]}" ] && echo -e "$( sed "${CMD_INFO[2]}q;d" "${CMD_INFO[1]}" | sed "s/^ *//g" | sed "s/^/#    /" )";
-        }
-      }
+          echo "# Stacktrace:"; [ -f "${CMD_INFO[1]}" ] && [ "${CMD_INFO[2]}" -le "$( wc -l < "${CMD_INFO[1]}" 2>&1 )" ] && {
+            echo "#   ${CMD_INFO[1]}:${CMD_INFO[2]} ${CMD_INFO[3]}"; echo "$( sed "${CMD_INFO[2]}q;d" "${CMD_INFO[1]}" | sed "s/^ *//g" | sed "s/^/#     /" )"; } || {
+            echo "#   ${CMD_INFO[3]}"; echo "#     ${CMD_INFO[4]}"; }; }; }
     done
   fi
 done; (( FAILED > 0 )) && exit 1 || exit 0
